# Generated by Django 4.2.4 on 2023-10-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFK', '0002_alter_studentmodel_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='Join_Date',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Std_Address',
            field=models.IntegerField(),
        ),
    ]
