# Generated by Django 4.2.4 on 2023-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFK', '0003_remove_studentmodel_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='Course_Fees',
            field=models.CharField(max_length=70),
        ),
    ]
